name = "hexxytest3"
author = "chloe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec0e8621bb76e4afb3298286034da02251e9639fc2309da54338fc4f65b00608"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
